### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by thatsjet** [fastoe/RTL8812BU_for_Raspbian#1]
Just want to say thanks for this. Running an older Raspberry Pi Model 2 B+ w/o wifi and the mini dongles haven't had much range. Bought a dongle off Amazon w/external antenna in hopes of getting more range but couldn't for the life of me find a driver that worked.

Yours worked flawlessly... on the first try. So... thanks. You rock.

**Comment by fastoe** [comment]
> Just want to say thanks for this. Running an older Raspberry Pi Model 2 B+ w/o wifi and the mini dongles haven't had much range. Bought a dongle off Amazon w/external antenna in hopes of getting more range but couldn't for the life of me find a driver that worked.
> 
> Yours worked flawlessly... on the first try. So... thanks. You rock.

Happy to help :)
