### ISSUE TITLE
Why are you deleting issues 😡. Problem still remains???

### ISSUE THREAD

**Issue by bitsvital** [fastoe/RTL8812BU_for_Raspbian#1]
I opened an issue yesterday. There were about five issues opened. Other users in the past month reported the same issue. I logged in today to see if there were any updates. You delete all the issues. Why 😡? The problem still remains.
I sent a message on Amazon with the full details. The response I received was:

Hi, clone the v5.6.1 branch and make:

sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot

That's what I had done PREVIOUSLY per your README.md file just like another user wrote in their issue. The problem still remains!

If you flash Raspberry PI lite and you DO NOT follow your instructions and DO NOT do an apt update it works. But when you do an apt upgrade Raspberry Pi has a new kernel in their repository. It installs version 5.10.11-v71+ which makes the dongle inoperable.

If you try to install the software OR you try a fresh install following your instructions you receive this error when you run make.

`make[2]: *** [scripts/Makefile.build:279: /home/pi/RTL8812BU_for_Raspbian-master/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1808: /home/pi/RTL8812BU_for_Raspbian-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.11-v7l+'
make: *** [Makefile:2290: modules] Error 2`

**Comment by fastoe** [comment]
Due to the old code repository without code flow, so we rebuild the code repository with code flow. In addition, the problems on github are all problems caused by the new kernel, after we updated the new code, these problems have been resolved.

**Comment by fastoe** [comment]
What version of your RPi kernel?

**Comment by bitsvital** [comment]
I have tried several times. And I keep obtaining this error:
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.4.83-v7l+/build M=/home/pi/RTL8812BU_for_Raspbian-master  modules
make[1]: *** /lib/modules/5.4.83-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:2290: modules] Error 2

I flash Raspberry Pi.
As long as I don't run apt update per your instructions I can install the driver and it works per the instructions.
However, when I run apt upgrade after the installation or after the installation the driver stop workings and gives the error above. The apt upgrade install kernel
5.10.11-v7l+

When I install OpenMediaVault it automatically updates and the WiFi adapter is useless.

Please help.

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:

sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot
