### ISSUE TITLE
error redefinition of ‘struct sha256_state’  struct sha256_state

### ISSUE THREAD

**Issue by clutch2sft** [fastoe/RTL8812BU_for_Raspbian#2]
<command-line>: note: this is the location of the previous definition
In file included from /home/pi/RTL8812BU_for_Raspbian/include/drv_types.h:79,
                 from /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
/home/pi/RTL8812BU_for_Raspbian/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
 struct sha256_state {
        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:24,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/pi/RTL8812BU_for_Raspbian/include/osdep_service_linux.h:48,
                 from /home/pi/RTL8812BU_for_Raspbian/include/osdep_service.h:50,
                 from /home/pi/RTL8812BU_for_Raspbian/include/drv_types.h:27,
                 from /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
 struct sha256_state {
        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1808: /home/pi/RTL8812BU_for_Raspbian] Error 2
make[1]: Leaving directory '/home/pi/linux-6af8ae321a801a4e20183454c65eb0d23069d8ac'
make: *** [Makefile:2290: modules] Error 2

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:

git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian.git
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot
