### ISSUE TITLE
Tested on Raspberry B, 3B+, 4

### ISSUE THREAD

**Issue by bitsvital** [fastoe/RTL8812BU_for_Raspbian#3]
I tested on three Raspberry Pi using Raspberry Pi Lite OS. Absolutely no problem.

**Comment by fastoe** [comment]
I also tested on Raspberry Pi 2, Raspberry Pi 3B+, Raspberry Pi 4B, Raspberry Pi Zero W with kernel version 5.4, no problem.

**Comment by bitsvital** [comment]
> I also tested on Raspberry Pi 2, Raspberry Pi 3B+, Raspberry Pi 4B, Raspberry Pi Zero W with kernel version 5.4, no problem.

I just test on a Pi Zero and Pi Zero W (w and w/out WiFi) and it works like a charm.
