### ISSUE TITLE
error: ‘struct cfg80211_ops’ has no member named ‘mgmt_frame_register’

### ISSUE THREAD

**Issue by clutch2sft** [fastoe/RTL8812BU_for_Raspbian#3]
error: ‘struct cfg80211_ops’ has no member named ‘mgmt_frame_register’
  .mgmt_frame_register = cfg80211_rtw_mgmt_frame_register,
   ^~~~~~~~~~~~~~~~~~~
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:9919:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, u64)’ {aka ‘int (*)(struct wiphy *, struct wireless_dev *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct wiphy *, struct wireless_dev *, u16,  bool)’ {aka ‘void (*)(struct wiphy *, struct wireless_dev *, short unsigned int,  _Bool)’} [-Werror=incompatible-pointer-types]
  .mgmt_frame_register = cfg80211_rtw_mgmt_frame_register,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:9919:25: note: (near initialization for ‘rtw_cfg80211_ops.mgmt_tx_cancel_wait’)
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c: In function ‘cfg80211_rtw_change_iface’:
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:2399:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
   is_p2p = _TRUE;
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:2401:2: note: here
  case NL80211_IFTYPE_STATION:
  ^~~~
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:2423:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
   is_p2p = _TRUE;
/home/pi/RTL8812BU_for_Raspbian/os_dep/linux/ioctl_cfg80211.c:2425:2: note: here
  case NL80211_IFTYPE_AP:
  ^~~~
cc1: some warnings being treated as errors

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:

git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian.git
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot

**Comment by clutch2sft** [comment]
My apologies for not reading all the way to the bottom.  Thank you for your quick reply.
