### ISSUE TITLE
Any chance of updating for latest kernel Linux raspberrypi 5.10.23-v7+ ?

### ISSUE THREAD

**Issue by jonas740** [fastoe/RTL8812BU_for_Raspbian#4]
I have tried to install this driver on most of mi RPI but since the current kernel is Linux raspberrypi 5.10.23-v7+ it fails.

I havent done a lot of creations of drivers so i do not have the know how. Mainly been doing ASM coding in the past so that will not help a lot here.

Any chance you could update the support for this driver ? Would be much appreciated.

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:
sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot

**Comment by jonas740** [comment]
Hello.

That actually did not work. It does however work for kernel 5.10.17-v7+.

I ended up building another driver first time around and yesterday i tried yours. What i found when using your driver was that the mac adress of wlan0 keeps changing at every reboot of the pi. 

so i created the following `/etc/NetworkManager/conf.d/100-disable-wifi-mac-randomization.conf`

and in that file i inserted the following

`[connection]`
`wifi.mac-address-randomization=1`
 
`[device]`
`wifi.scan-rand-mac-address=no`

That ended up to work as planned.

The driver i used first time when i got it to work was from [https://github.com/cilynx/rtl88x2bu.git](url)

And i ofc changed thoose two lines.
CONFIG_PLATFORM_I386_PC = n
CONFIG_PLATFORM_ARM_RPI = y

**Comment by fastoe** [comment]
Hi, the latest kernel version officially released is 5.10.17-v7l+, where to download the kernel 5.10.23-v7 version of the firmware?

**Comment by stevenjoezhang** [comment]
I encountered a similar issue. The kernel version is 5.10.17 in the latest raspbian OS mirror. However the kernel can be upgraded through the `apt upgrade` command, and the official firmware is updated to 5.10.63 in this repository: https://github.com/raspberrypi/firmware

<img width="660" alt="截屏2021-09-12 下午5 22 27" src="https://user-images.githubusercontent.com/16272760/132982231-b9ccf570-99e0-4797-b79a-5bac9a299cf3.png">

**Comment by fastoe** [comment]
@stevenjoezhang Thanks, we have updated the 8812bu 5.8.7 driver, It can be compiled on kernel 5.10.60-v8+.

uname -a
`Linux raspberrypi 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux`

```
sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.8.7 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot
```
