### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by SmoochiesBoss** [fastoe/RTL8812BU_for_Raspbian#5]
Followed the simple instructions on the Linux install guide. Doesn't work. 
Found the simple instructions in these three issues. Doesn't work. 
I purchased this adapter for simple installation on my Pi. Please help.

`
pi@raspberrypi:~/RTL8812BU_for_Raspbian $ make
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.11-v7+/build M=/home/pi/RTL8812BU_for_Raspbian  modules
make[1]: *** /lib/modules/5.10.11-v7+/build: No such file or directory.  Stop.
make: *** [Makefile:2284: modules] Error 2
`

**Comment by SmoochiesBoss** [comment]
`pi@raspberrypi:/lib/modules $ ls
5.10.17+  5.10.17-v7+  5.10.17-v7l+  5.10.17-v8+
`

**Comment by SmoochiesBoss** [comment]
For anyone else out there, reboot before you run make in the given instructions. That got me to the next step.

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:
sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot
