### ISSUE TITLE
make on RPI4B return error

### ISSUE THREAD

**Issue by nilm987521** [fastoe/RTL8812BU_for_Raspbian#8]
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.17-v7l+/build M=/home/pi/RTL8812BU_for_Raspbian  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.17-v7l+'
  CC [M]  /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.o
In file included from /home/pi/RTL8812BU_for_Raspbian/include/drv_conf.h:17,
                 from /home/pi/RTL8812BU_for_Raspbian/include/drv_types.h:25,
                 from /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
/home/pi/RTL8812BU_for_Raspbian/include/autoconf.h:183: warning: "CONFIG_RTW_SW_LED" redefined
  #define CONFIG_RTW_SW_LED
 
<command-line>: note: this is the location of the previous definition
In file included from /home/pi/RTL8812BU_for_Raspbian/include/drv_types.h:79,
                 from /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
/home/pi/RTL8812BU_for_Raspbian/include/rtw_security.h:257:8: error: redefinition of ‘struct sha256_state’
 struct sha256_state {
        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:24,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/pi/RTL8812BU_for_Raspbian/include/osdep_service_linux.h:48,
                 from /home/pi/RTL8812BU_for_Raspbian/include/osdep_service.h:5,
                 from /home/pi/RTL8812BU_for_Raspbian/include/drv_types.h:27,
                 from /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
 struct sha256_state {
        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /home/pi/RTL8812BU_for_Raspbian/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1804: /home/pi/RTL8812BU_for_Raspbian] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.17-v7l+'
make: *** [Makefile:2290: modules] Error 2

**Comment by fastoe** [comment]
For 5.10 kernel, please clone the v5.6.1 branch:

sudo apt update
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU_for_Raspbian
cd RTL8812BU_for_Raspbian
make
sudo make install
sudo reboot

**Comment by nilm987521** [comment]
thank you very much

Fastoe ***@***.***> 於 2021年7月29日 週四 下午4:39寫道：
